paths:
  /store/reviews/{storeId}:
   post:
      tags:
        - Store
      summary: 리뷰 작성
      parameters:
       - name: storeId
          in: path
          schema:
            type: integer
          required: true
        - name: review
          in: body
          required: true
          schema:
            properties:
              memberId:
                type: integer
                description: 유저 pk
                example: 1
              storeId:
                type: integer
                description: 가게 pk
                example: 1
              body:
                type: string
                description: 리뷰 내용
                example: 굿
              score:
                type: float
                description: 점수
                example: 2.1
      responses:
        "200":
          description: 리뷰 작성 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: String
                example: 리뷰 작성 성공

        "400":
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        "500":
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.

paths:
  /store/missions/{storeId}:
    get:
      tags:
        - Store
      summary: 가게 별 미션 목록 조회
      parameters:
        - name: storeId
          in: path
          schema:
            type: integer
          required: true
        - name: missionId
          in: query
          required: false
          schema:
            properties:
              reviewId:
                type: integer
        - name: paging
          in: query
          required: true
          schema:
            properties:
              size:
                type: integer
      responses:
        "200":
          description: 미션 조회 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: array
                example:
                  {
                    "missionData":
                      [
                        {
                          "store_id": 1,
                          "reward": 5,
                          "deadline" : "2000.01.02",
                          "mission_spec": "미션1",
                          "create_date": "2000.01.01",
                        },
                        {
                          "store_id": 2,
                          "reward": 9,
                          "deadline" : "2000.01.02",
                          "mission_spec": "미션2",
                          "create_date": "2000.01.01",
                        },
                      ],
                    "cursorId": 1,
                  }

        "400":
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        "500":
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.

