paths:
  /user/signin:
    post:
      tags:
        - User
      summary: 회원가입
      parameters:
        - name: signIn
          in: body
          required: true
          schema:
            properties:
              email:
                type: string
                description: 유저 이메일
                example: swaggerTest@mail.com
              name:
                type: string
                description: 유저 이름
                example: swagger
              gender:
                type: string
                description: 유저 성별
                example: M
              birthYear:
                type: integer
                description: 생일 년도
                example: 2000
              birthMonth:
                type: integer
                description: 생일 월
                example: 1
              birthDay:
                type: integer
                description: 생일 일
                example: 31
              addr:
                type: string
                description: 주소
                example: swagger Test address
              specAddr:
                type: string
                description: 상세 주소
                example: swagger Test specAddr
              phone:
                type: string
                description: 전화 번호
                example: 010-0000-0000
              prefer:
                type: array
                description: 선호 카테고리 번호
                example: [1, 3, 5]
      responses:
        "200":
          description: 회원 가입 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example:
                  {
                    "email": "swaggerTest@mail.com",
                    "name": "swagger",
                    "preferCategory": ["한식", "일식"],
                  }

        "400":
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        "500":
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.

paths:
  /user/reviews/{memberId}:
    get:
      tags:
        - User
      summary: 내가 쓴 리뷰 조회 로직
      parameters:
        - name: memberId
          in: path
          schema:
            type: integer
          required: true
        - name: reviewId
          in: query
          required: false
          schema:
            properties:
              reviewId:
                type: integer
        - name: paging
          in: query
          required: true
          schema:
            properties:
              size:
                type: integer
      responses:
        "200":
          description: 리뷰 조회 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: array
                example:
                  {
                    "reviewData":
                      [
                        {
                          "user_name": "SwaggerTest1",
                          "rate": 5,
                          "review_body": "리뷰1",
                          "create_date": "2000.01.01",
                        },
                        {
                          "user_name": "SwaggerTest2",
                          "rate": 4.5,
                          "review_body": "리뷰2",
                          "create_date": "2000.02.02",
                        },
                      ],
                    "cursorId": 1,
                  }

        "400":
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        "500":
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.


paths:
  /user/missions/{memberId}:
    get:
      tags:
        - User
      summary: 내 미션 목록 조회
      parameters:
        - name: storeId
          in: path
          schema:
            type: integer
          required: true
        - name: missionId
          in: query
          required: false
          schema:
            properties:
              reviewId:
                type: integer
        - name: paging
          in: query
          required: true
          schema:
            properties:
              size:
                type: integer
      responses:
        "200":
          description: 미션 조회 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: array
                example:
                  {
                    "missionData":
                      [
                        {
                          "store_id": 1,
                          "reward": 5,
                          "deadline" : "2000.01.02",
                          "mission_spec": "미션1",
                          "create_date": "2000.01.01",
                        },
                        {
                          "store_id": 2,
                          "reward": 9,
                          "deadline" : "2000.01.02",
                          "mission_spec": "미션2",
                          "create_date": "2000.01.01",
                        },
                      ],
                    "cursorId": 1,
                  }

        "400":
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        "500":
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
